version: '3.5'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build: .
    container_name: app
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=super_admin
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres

    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"



volumes:
  app:
    driver: local
  postgres-db:
    driver: local